Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
   end


  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y \
         apt-transport-https \
         ca-certificates \
         curl \
         software-properties-common
    
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    sudo add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable"
    
    sudo apt-get update

    sudo apt-get install -y\
        linux-image-extra-$(uname -r) \
        linux-image-extra-virtual

    sudo apt-get install -y docker-ce

    curl -L https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

    sudo chmod +x /usr/local/bin/docker-compose
        
  SHELL
end